apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rixybtb5z-dotnet-basic
  janus-idp.io/tekton: rixybtb5z-dotnet-basic
  backstage.io/kubernetes-id: rixybtb5z-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rixybtb5z-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
